### ISSUE TITLE
Dropdown button is not disabled 

### ISSUE THREAD

**Issue by RoaringSilence** [bimobject/bim-select#7]
When using ng-disabled the right-hand "arrow down" button is not disabled properly nor grayed out.

![image](https://user-images.githubusercontent.com/23187663/33163469-f59ac724-d02e-11e7-911b-f88787a64ee9.png)

**Comment by tregusti** [comment]
I'm sorry for taking so long to look into this.

If you open the `examples/bootstrap.html` file and toggle the disabled checkbox on the topmost dropdown, doesn't it gray out the arrow and the border around it then? It does for me. So I think there is something else going on in your code that make your styling behave as it does.

![](https://i.imgur.com/3EhQ4qj.gif)
